# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Create directories and download jar files
      run: |
        mkdir -p $HOME/.steam/steam/steamapps/workshop/content/646570/1605060445/
        mkdir -p $HOME/.steam/steam/steamapps/workshop/content/646570/1605833019/
        mkdir -p $HOME/.steam/steam/steamapps/workshop/content/646570/1609158507/
        mkdir -p $HOME/.steam/steam/steamapps/common/SlayTheSpire/
        curl -L -o $HOME/.steam/steam/steamapps/workshop/content/646570/1605060445/ModTheSpire.jar "https://github.com/hyperv0id/lingmod/releases/download/dependency/ModTheSpire.jar"
        curl -L -o $HOME/.steam/steam/steamapps/workshop/content/646570/1605833019/BaseMod.jar "https://github.com/hyperv0id/lingmod/releases/download/dependency/BaseMod.jar"
        curl -L -o $HOME/.steam/steam/steamapps/workshop/content/646570/1609158507/StSLib.jar "https://github.com/hyperv0id/lingmod/releases/download/dependency/StSLib.jar"
        curl -L -o $HOME/.steam/steam/steamapps/common/SlayTheSpire/desktop-1.0.jar "https://github.com/hyperv0id/lingmod/releases/download/dependency/desktop-1.0.jar"
    - name: Verify download
      run: tree $HOME/.steam/steam/steamapps/
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: LingMod.jar
        path: target/*.jar

  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: LingMod.jar
    - name: List files
      run: ls -l
