name: Release

on:
  push

jobs:
  build:
    uses: ./.github/workflows/maven-build.yml  # 依赖maven-build工作流

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Download JAR
      uses: actions/download-artifact@v4
      with:
        name: LingMod.jar
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./LingMod.jar
        asset_name: LingMod.jar
        asset_content_type: application/java-archive
